# Site settings
title: Noizbuster's Base
email: NoizBuster@NoizBuster.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://Noizbuster.com" # the base hostname & protocol for your site
twitter_username: noizbuster
github_username:  noizbuster

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: NoizBuster's Naver Blog
    link: http://blog.naver.com/noizbuster
  # option2:
  #   name: Cool Option 2
  #   link: www.myawesomelink.com
  # option3:
  #   name: Cool Option 3
  #   link: www.myawesomelink.com

disqus: false
disqus_shortname: 'Noiz'

# Build settings
markdown: kramdown
